export const CHANGE_BG_DARKER = 'CHANGE_BG_DARKER';
export const CHANGE_BG_MIXED = 'CHANGE_BG_MIXED';
export const CHANGE_MAIN_COLOR = 'CHANGE_MAIN_COLOR';
export const CHANGE_MIXED_COLOR = 'CHANGE_MIXED_COLOR';
export const CHANGE_DARKER_ARRAY = 'CHANGE_DARKER_ARRAY';
export const CHANGE_MIXED_ARRAY = 'CHANGE_MIXED_ARRAY';
export const SELECT_DARKER_ITEM = 'SELECT_DARKER_ITEM';
export const SELECT_MIXED_ITEM = 'SELECT_MIXED_ITEM';
export const SELECT_FLAT_ITEM = 'SELECT_FLAT_ITEM';
export const SELECT_SCHEME_ITEM = 'SELECT_SCHEME_ITEM';
export const SELECT_MATERIAL_ITEM = 'SELECT_MATERIAL_ITEM';
export const SELECT_ALL_DARKER_ITEMS = 'SELECT_ALL_DARKER_ITEMS';
export const SELECT_ALL_MIXED_ITEMS = 'SELECT_ALL_MIXED_ITEMS';
export const REMOVE_ALL_DARKER_ITEMS = 'REMOVE_ALL_DARKER_ITEMS';
export const REMOVE_ALL_MIXED_ITEMS = 'REMOVE_ALL_MIXED_ITEMS';
export const REMOVE_SELECTED_COLOR = 'REMOVE_SELECTED_COLOR';


